import React, { useState } from 'react';
import {
  Cpu,
  Search,
  SlidersHorizontal,
  ChevronDown,
  ChevronUp,
  Layers,
  Sparkles,
  AlertTriangle,
  Compass,
  FileCode2,
  ShieldAlert,
  Info,
  ExternalLink,
} from 'lucide-react';
import ModuleAccordion from './ModuleAccordion';
import Badge from '../common/Badge';
import Button from '../common/Button';

/**
 * Explanation View Component (Phase 6)
 * @param {Object} props
 * @param {Object} props.explanation - Explanation payload from /api/jobs/{job_id}/results
 */
export default function ExplanationView({ explanation = {} }) {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedLanguage, setSelectedLanguage] = useState('all');
  const [expandAll, setExpandAll] = useState(false);

  const {
    overview = 'Comprehensive architectural overview generated by CodeOracle AI pipeline.',
    architecture_pattern = 'Monolithic / Modular',
    entry_points = [],
    modules = [],
    risks = [],
    limitations = [],
  } = explanation;

  // Filter modules by search and language
  const filteredModules = modules.filter((mod) => {
    const matchesSearch =
      mod.name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
      mod.path?.toLowerCase().includes(searchQuery.toLowerCase()) ||
      mod.explanation?.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesLang =
      selectedLanguage === 'all' ||
      mod.language?.toLowerCase() === selectedLanguage.toLowerCase();

    return matchesSearch && matchesLang;
  });

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      {/* 1. Executive Project Overview Card */}
      <div className="rounded-3xl bg-[#0f111e]/90 border border-white/[0.08] p-6 sm:p-8 backdrop-blur-xl shadow-xl shadow-black/30 space-y-4 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-purple-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="flex items-center justify-between gap-3 border-b border-white/[0.06] pb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-purple-500/20 border border-purple-500/30 flex items-center justify-center text-purple-400">
              <Cpu className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base sm:text-lg font-bold text-slate-100 tracking-tight">
                Executive Architecture Overview
              </h3>
              <p className="text-xs text-slate-400">
                Pattern: <strong className="text-cyan-300 font-mono">{architecture_pattern}</strong>
              </p>
            </div>
          </div>

          <Badge variant="purple" size="sm" dot>
            AST & LLM Analyzed
          </Badge>
        </div>

        <p className="text-sm text-slate-300 leading-relaxed font-light">
          {overview}
        </p>

        {/* Entry Points Badges */}
        {entry_points && entry_points.length > 0 && (
          <div className="pt-3 border-t border-white/[0.04]">
            <span className="text-[11px] font-mono uppercase tracking-wider text-slate-400 block mb-2 flex items-center gap-1.5">
              <Compass className="w-3.5 h-3.5 text-cyan-400" />
              <span>Identified Application Entry Points:</span>
            </span>
            <div className="flex flex-wrap gap-2">
              {entry_points.map((ep, idx) => (
                <div
                  key={idx}
                  className="px-3 py-1.5 rounded-xl bg-white/[0.03] border border-white/10 flex items-center gap-2 text-xs font-mono text-slate-200"
                >
                  <span className="w-1.5 h-1.5 rounded-full bg-cyan-400" />
                  <span>{typeof ep === 'object' ? `${ep.name} (${ep.type || 'entry'})` : ep}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* 2. Module Explanations Section */}
      <div className="space-y-4">
        {/* Controls bar: Search, Filter, Expand/Collapse */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <h4 className="text-base font-bold text-slate-100 tracking-tight">
              Module Explanations ({filteredModules.length})
            </h4>
          </div>

          <div className="flex items-center gap-3">
            {/* Search Input */}
            <div className="relative flex-1 sm:w-64">
              <Search className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search modules or functions..."
                className="w-full pl-9 pr-3 py-1.5 rounded-xl bg-[#0a0b12] border border-white/10 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-purple-500/50"
              />
            </div>

            {/* Quick Expand Toggle */}
            <Button
              variant="outline"
              size="sm"
              onClick={() => setExpandAll(!expandAll)}
              className="text-xs shrink-0"
            >
              {expandAll ? 'Collapse All' : 'Expand All'}
            </Button>
          </div>
        </div>

        {/* Modules Accordion List */}
        {filteredModules.length > 0 ? (
          <div className="space-y-3">
            {filteredModules.map((mod, idx) => (
              <ModuleAccordion
                key={mod.name || idx}
                module={mod}
                defaultOpen={expandAll || idx === 0}
              />
            ))}
          </div>
        ) : (
          <div className="text-center py-12 bg-[#0f111e]/50 rounded-2xl border border-white/[0.06] text-slate-400 text-xs space-y-2">
            <Info className="w-5 h-5 mx-auto text-purple-400 opacity-60" />
            <p>No modules matched your search query "{searchQuery}".</p>
          </div>
        )}
      </div>

      {/* 3. Risks & Limitations Section */}
      {(risks.length > 0 || limitations.length > 0) && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Architectural Risks */}
          {risks.length > 0 && (
            <div className="p-5 rounded-2xl bg-rose-950/20 border border-rose-500/25 space-y-2 text-xs">
              <div className="flex items-center gap-2 text-rose-300 font-semibold">
                <ShieldAlert className="w-4 h-4 text-rose-400 shrink-0" />
                <span>Identified Architectural Risks ({risks.length})</span>
              </div>
              <ul className="space-y-1.5 pl-5 list-disc text-slate-300 leading-relaxed">
                {risks.map((r, i) => (
                  <li key={i}>{typeof r === 'object' ? r.description || r.message : r}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Analysis Limitations */}
          {limitations.length > 0 && (
            <div className="p-5 rounded-2xl bg-indigo-950/20 border border-indigo-500/25 space-y-2 text-xs">
              <div className="flex items-center gap-2 text-indigo-300 font-semibold">
                <Info className="w-4 h-4 text-indigo-400 shrink-0" />
                <span>Analysis Caveats & Limitations</span>
              </div>
              <ul className="space-y-1.5 pl-5 list-disc text-slate-300 leading-relaxed">
                {limitations.map((l, i) => (
                  <li key={i}>{typeof l === 'object' ? l.description || l.message : l}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
